---
title: "dplyr Homework"
subtitle: "Week 03, Day 1; Homework"
author: "Miles Drake"
date: 2020-03-09
output:
  html_document:
    df_print: paged
    number_sections: true
    toc: true
    toc_float: true
---

```{r knitr, include = FALSE}
knitr::opts_chunk$set(error = FALSE, message = FALSE, warning = FALSE)
```

```{r libraries}
library(tidyverse)
```

# MVP

##

```{r}
drinks <- read_csv("data/starbucks_drinkMenu_expanded.csv")
```

```{r}
head(drinks, 5)
tail(drinks, 5)
drinks
```

##

```{r eval = FALSE}
drinks$Calories <- gsub("-", NA, drinks$Calories)
drinks$`Fat (g)` <- gsub("-", NA, drinks$`Fat (g)`)
drinks$`Carb. (g)` <- gsub("-", NA, drinks$`Carb. (g)`)
drinks$`Fiber (g)` <- gsub("-", NA, drinks$`Fiber (g)`)
drinks$Protein <- gsub("-", NA, drinks$Protein)
drinks$Sodium <- gsub("-", NA, drinks$Sodium)

drinks$Calories <- as.integer(drinks$Calories)
drinks$`Fat (g)` <- as.integer(drinks$`Fat (g)`)
drinks$`Carb. (g)` <- as.integer(drinks$`Carb. (g)`)
drinks$`Fiber (g)` <- as.integer(drinks$`Fiber (g)`)
drinks$Protein <- as.integer(drinks$Protein)
drinks$Sodium <- as.integer(drinks$Sodium)
```


```{r}
summary_statistics <- list()
summary_statistics$mean <- mean(drinks$Calories, na.rm = TRUE)
summary_statistics$variance <- var(drinks$Calories, na.rm = TRUE)
hist(drinks$Calories)
```

##

```{r}
outlier_ids <- boxplot(
  drinks$Calories
)$out
```

```{r}
filter(
  drinks,
  Calories %in% outlier_ids
)
```

##

```{r}
select(drinks, Beverage_category, Beverage, Beverage_prep, Calories)
```

##

```{r}
filter(
  drinks,
  Beverage_category == "Classic Espresso Drinks"
)
```

##

```{r}
drink_calories <- as_tibble(
  drinks %>%
    select(Beverage_category, Beverage, Beverage_prep, Calories) %>%
    mutate(
      calorie_diff = Calories - 135
    ) %>%
    arrange(
      desc(Calories),
      Beverage_category,
      Beverage
    )
)
```

```{r}
drink_calories
```

