<!DOCTYPE html>
<html lang="en-gb">
<head><meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Introduction to `ggplot2` Homework - Miles Drake&#39;s CodeClan Homework</title>
<meta name="description" content="DE3 (data analysis) cohort">
<meta name="generator" content="Hugo 0.65.3" />
<link href="../../../index.xml" rel="alternate" type="application/rss+xml">
<link rel="canonical" href="../../../week-05/day-1/ggplot/">
<link rel="stylesheet" href="../../../css/theme.min.css">
<script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<link rel="stylesheet" href="../../../css/chroma.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.easing@1.4.1/jquery.easing.min.js"></script>
<script src="../../../js/bundle.js"></script><style>
:root {}
</style>
<meta property="og:title" content="Introduction to `ggplot2` Homework" />
<meta property="og:description" content="library(CodeClanData)library(tidyverse)MVPQuestion 1Load in the libraries you need, and look at the backpack data. Take note of variable names and dimensions.
head(backpack)## backpack_weight body_weight ratio back_problems major year sex## 1 9 125 0.0720000 1 Bio 3 Female## 2 8 195 0.0410256 0 Philosophy 5 Male## 3 10 120 0.0833333 1 GRC 4 Female## 4 6 155 0.0387097 0 CSC 6 Male## 5 8 180 0." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/week-05/day-1/ggplot/" />
<meta property="og:image" content="/images/og-image.png"/>
<meta property="article:published_time" content="2020-04-01T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-04-01T00:00:00+00:00" /><meta property="og:site_name" content="Hugo Techdoc Theme" />
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="/images/og-image.png"/>

<meta name="twitter:title" content="Introduction to `ggplot2` Homework"/>
<meta name="twitter:description" content="library(CodeClanData)library(tidyverse)MVPQuestion 1Load in the libraries you need, and look at the backpack data. Take note of variable names and dimensions.
head(backpack)## backpack_weight body_weight ratio back_problems major year sex## 1 9 125 0.0720000 1 Bio 3 Female## 2 8 195 0.0410256 0 Philosophy 5 Male## 3 10 120 0.0833333 1 GRC 4 Female## 4 6 155 0.0387097 0 CSC 6 Male## 5 8 180 0."/>
<meta itemprop="name" content="Introduction to `ggplot2` Homework">
<meta itemprop="description" content="library(CodeClanData)library(tidyverse)MVPQuestion 1Load in the libraries you need, and look at the backpack data. Take note of variable names and dimensions.
head(backpack)## backpack_weight body_weight ratio back_problems major year sex## 1 9 125 0.0720000 1 Bio 3 Female## 2 8 195 0.0410256 0 Philosophy 5 Male## 3 10 120 0.0833333 1 GRC 4 Female## 4 6 155 0.0387097 0 CSC 6 Male## 5 8 180 0.">
<meta itemprop="datePublished" content="2020-04-01T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2020-04-01T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="691">
<meta itemprop="image" content="/images/og-image.png"/>



<meta itemprop="keywords" content="" /></head>
<body><div class="container"><header>
<h1>Miles Drake&#39;s CodeClan Homework</h1>
<a href="https://github.com/thingsym/hugo-theme-techdoc" class="github"><i class="fab fa-github"></i></a>
<p class="description">DE3 (data analysis) cohort</p>

</header>
<div class="global-menu">
<nav>
<ul>
<li><a href="../../../">Home</a></li>
<li><a href="https://twitter.com/thingsym">Twitter</a></li></ul>
</nav>
</div>
<div class="content-container">
<main><h1>Introduction to `ggplot2` Homework</h1>



<pre class="r"><code>library(CodeClanData)
library(tidyverse)</code></pre>
<div id="mvp" class="section level1">
<h1>MVP</h1>
<div id="question-1" class="section level2">
<h2>Question 1</h2>
<p>Load in the libraries you need, and look at the backpack data. Take note of variable names and dimensions.</p>
<pre class="r"><code>head(backpack)</code></pre>
<pre><code>##   backpack_weight body_weight     ratio back_problems      major year    sex
## 1               9         125 0.0720000             1        Bio    3 Female
## 2               8         195 0.0410256             0 Philosophy    5   Male
## 3              10         120 0.0833333             1        GRC    4 Female
## 4               6         155 0.0387097             0        CSC    6   Male
## 5               8         180 0.0444444             0         EE    2 Female
## 6               5         240 0.0208333             0    History    0   Male
##   status units
## 1      U    13
## 2      U    12
## 3      U    14
## 4      G     0
## 5      U    14
## 6      G     0</code></pre>
</div>
<div id="question-2" class="section level2">
<h2>Question 2</h2>
<p>What is the distribution of backpack weights that students are carrying? Choose an appropriate graph to show the distribution.</p>
<pre class="r"><code>backpack %&gt;% 
  ggplot() +
  geom_histogram() +
  aes(
    x = backpack_weight
  ) +
  labs(
    x = &quot;Backpack Weight&quot;,
    y = &quot;Count&quot;,
    title = &quot;Backpack Weight&quot;,
    subtitle = &quot;Weight of backpack carried by higher education students&quot;
  )</code></pre>
<p><img src="../../../week-05/day-1/ggplot_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The above histogram shows that the backpack weight follows an approximately normal distribution with a positive skew.</p>
</div>
<div id="question-3" class="section level2">
<h2>Question 3</h2>
<p>Are there differences in backpack weight between sex?</p>
<pre class="r"><code>backpack %&gt;% 
  ggplot() +
  geom_histogram() +
  aes(
    x = backpack_weight,
    fill = sex
  ) +
  labs(
    x = &quot;Backpack Weight&quot;,
    y = &quot;Count&quot;,
    title = &quot;Backpack Weight&quot;,
    subtitle = &quot;Weight of backpack carried by higher education students&quot;
  ) +
  facet_wrap(
    ~sex
  )</code></pre>
<p><img src="../../../week-05/day-1/ggplot_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Both sexes follow approximately the same distribution, but the data for female students is more clustered around the median value of 11.</p>
</div>
<div id="question-4" class="section level2">
<h2>Question 4</h2>
<p>What is the relationship between body weight and backpack weight?</p>
<pre class="r"><code>backpack %&gt;% 
  ggplot() +
  geom_point() +
  geom_smooth() +
  aes(
    x = backpack_weight,
    y = body_weight
  ) +
  labs(
    x = &quot;Backpack Weight&quot;,
    y = &quot;Body Weight&quot;,
    title = &quot;Backpack Weight and Body Weight&quot;,
    subtitle = &quot;Weight of backpack carried by higher education students&quot;
  )</code></pre>
<p><img src="../../../week-05/day-1/ggplot_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>There appears to be no relationship between backpack weight and body weight. There is, at a stretch, a very weak positive correlation.</p>
</div>
<div id="question-5" class="section level2">
<h2>Question 5</h2>
<p>Is this relationship different between men and women? Choose an appropriate plot and interpret your findings.</p>
<pre class="r"><code>backpack %&gt;% 
  ggplot() +
  geom_point() +
  geom_smooth() +
  aes(
    x = backpack_weight,
    y = body_weight,
    fill = sex
  ) +
  labs(
    x = &quot;Backpack Weight&quot;,
    y = &quot;Body Weight&quot;,
    title = &quot;Backpack Weight Against Body Weight&quot;,
    subtitle = &quot;Weight of backpack carried by higher education students&quot;
  ) +
  facet_wrap(
    ~sex
  )</code></pre>
<p><img src="../../../week-05/day-1/ggplot_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The relationship appears to be the same when adjusted for sex, noting that one male student is exaggerating the correlation at the far end of the data.</p>
</div>
<div id="question-6" class="section level2">
<h2>Question 6</h2>
<p>What <strong>proportion</strong> of students report back pain?</p>
<pre class="r"><code>sum(backpack$back_problems) / length(backpack$back_problems) * 100</code></pre>
<pre><code>## [1] 32</code></pre>
<p>32% of students report back pain.</p>
</div>
<div id="question-7" class="section level2">
<h2>Question 7</h2>
<p>Is this proportion different between men and women?</p>
<pre class="r"><code>backpack_problems_male &lt;- backpack %&gt;% 
  filter(
    sex == &quot;Male&quot;
  ) %&gt;% 
  select(
    back_problems
  ) %&gt;% 
  as_vector() %&gt;% 
  as.logical()

backpack_problems_female &lt;- backpack %&gt;% 
  filter(
    sex == &quot;Female&quot;
  ) %&gt;% 
  select(
    back_problems
  ) %&gt;% 
  as_vector() %&gt;% 
  as.logical()</code></pre>
<pre class="r"><code>round(
  sum(backpack_problems_male) / length(backpack_problems_male) * 100,
  2
)</code></pre>
<pre><code>## [1] 17.78</code></pre>
<p>17.78% of male students report back pain.</p>
<pre class="r"><code>round(
  sum(backpack_problems_female) / length(backpack_problems_female) * 100,
  2
)</code></pre>
<pre><code>## [1] 43.64</code></pre>
<p>43.64% of female students report back pain. This is a total difference of female students being 25.86% more likely to report back pain.</p>
</div>
<div id="question-8" class="section level2">
<h2>Question 8</h2>
<p>Now you’ve investigated your data separately, create plots to describe the relationship between backpack weight, body weight, gender and reported backpain.</p>
<pre class="r"><code>backpack %&gt;% 
  ggplot() +
  geom_point() +
  geom_smooth(
    aes(
      fill = sex
    ),
    show.legend = FALSE
  ) +
  aes(
    x = backpack_weight,
    y = body_weight
  ) +
  labs(
    x = &quot;Backpack Weight&quot;,
    y = &quot;Body Weight&quot;,
    title = &quot;Backpack Weight Against Body Weight&quot;,
    subtitle = &quot;Weight of backpack carried by higher education students&quot;
  ) +
  facet_grid(
    ~sex ~back_problems,
    labeller = &quot;label_both&quot;
  )</code></pre>
<p><img src="../../../week-05/day-1/ggplot_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>We see that the paucity of male students who have reported back problems has resulted in very few data points in the male with back problems plot. An outlier in the male plot is stretching the length of the plot, though it does not appear to have a notable effect on the data.</p>
</div>
</div>
<div class="edit-meta">
Last updated on 1 Apr 2020


<br>
Published on 1 Apr 2020
<br><a href="https://github.com/apologyfestival/codeclan_homework_miles/edit/master/content/week-05%5cday-1%5cggplot.html" class="edit-page"><i class="fas fa-pen-square"></i> Edit on GitHub</a></div><nav class="pagination"><a class="nav nav-prev" href="../../../week-05/" title="Week-05s"><i class="fas fa-arrow-left" aria-hidden="true"></i> Prev - Week-05s</a>
<a class="nav nav-next" href="../../../week-06/" title="Week-06s">Next - Week-06s <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
</nav><footer><p class="powered">Powered by <a href="https://gohugo.io">Hugo</a>. Theme by <a href="https://themes.gohugo.io/hugo-theme-techdoc/">TechDoc</a>. Designed by <a href="https://github.com/thingsym/hugo-theme-techdoc">Thingsym</a>.</p>
</footer>
</main><div class="sidebar">

<nav class="open-menu">
<ul>
<li class=""><a href="../../../">Home</a></li>

<li class=""><a href="../../../week-03/">Week-03s</a>
  
<ul class="sub-menu">
<li class=""><a href="../../../week-03/day-3/codeclan-tweets/">Tidyverse Consolidation Homework</a></li>
<li class=""><a href="../../../week-03/day-2/1-world-bank-data/">World Bank Data</a></li>
<li class=""><a href="../../../week-03/day-1/1-dplyr/">dplyr Homework</a></li>
</ul>
  
</li>

<li class=""><a href="../../../week-04/">Week-04s</a>
  
<ul class="sub-menu">
<li class=""><a href="../../../week-04/day-1/1-decathlon/documentation_and_analysis/decathlon_analysis/">Decathlon Analysis</a></li>
<li class=""><a href="../../../week-04/day-1/6-dog-survey/documentation_and_analysis/dog_survey_documentation/">Dog Owners&#39; Survey</a></li>
</ul>
  
</li>

<li class="parent"><a href="../../../week-05/">Week-05s</a>
  
<ul class="sub-menu">
<li class="active"><a href="../../../week-05/day-1/ggplot/">Introduction to `ggplot2` Homework</a></li>
</ul>
  
</li>

<li class=""><a href="../../../week-06/">Week-06s</a>
  
<ul class="sub-menu">
<li class=""><a href="../../../week-06/day-3/confidence-intervals-minilab/">Confidence Intervals Minilab</a></li>
<li class=""><a href="../../../week-06/day-1/probability/">Probability</a></li>
<li class=""><a href="../../../week-06/day-2/distributions/"></a></li>
</ul>
  
</li>

<li class=""><a href="../../../week-02/">Week-02s</a>
  
<ul class="sub-menu">
<li class=""><a href="../../../week-02/day-2/connecting-to-remote-databases/">Connecting to Remote Databases in R</a></li>
<li class=""><a href="../../../week-02/day-1/reading-in-data/">Reading in Data</a></li>
<li class=""><a href="../../../week-02/day-5/1-sql/"></a></li>
</ul>
  
</li>

<li class=""><a href="../../../week-01/">Week-01s</a>
  
<ul class="sub-menu">
<li class=""><a href="../../../week-01/day-5/conditionals-functions-loops/">Conditionals, Functions, and Loops</a></li>
<li class=""><a href="../../../week-01/day-3/1-best-practice/">Best Practice</a></li>
<li class=""><a href="../../../week-01/day-3/2-conflicts/">Errors</a></li>
<li class=""><a href="../../../week-01/day-2/data-types/">Data Types</a></li>
</ul>
  
</li>
</ul>
</nav>



<div class="sidebar-footer"></div>
</div>
</div><a href="#" id="backtothetop-fixed" class="backtothetop"
 data-backtothetop-duration="600"
 data-backtothetop-easing="easeOutQuart"
 data-backtothetop-fixed-fadeIn="1000"
 data-backtothetop-fixed-fadeOut="1000"
 data-backtothetop-fixed-bottom="10"
 data-backtothetop-fixed-right="20">
<span class="fa-layers fa-fw">
<i class="fas fa-circle"></i>
<i class="fas fa-arrow-circle-up"></i>
</span></a>
</div>
</body>
</html>
