---
title: "Connecting to Remote Databases in R"
subtitle: "Week 02, Day 2; Homework"
author: "Miles Drake"
date: 2020-03-03
output:
  html_document:
    number_sections: true
    toc: true
    toc_float: true
---

```{r knitr, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
knitr::opts_chunk$set(eval = FALSE)
```

```{r libraries}
library(keyring)
library(RPostgreSQL)
```

# MVP

## Local PostgreSQL Connections

```{r}
keyring_unlock("local")
local_db <- dbConnect(
  drv = PostgreSQL(),
  user = key_get("postgresql_username", keyring = "local"),
  password = key_get("postgresql_password", keyring = "local"),
  dbname = "wrestling",
  host = "localhost"
)
keyring_lock("local")
```

### List of Wrestlers

```{r}
dbGetQuery(
  local_db,
  "SELECT * FROM wrestlers"
)
```

### Data Types

- id: int
- born: chr
- name: chr
- gender: chr
- win_percent: dbl
- total_matches: int

## Remote PostgreSQL Connections

```{r}
keyring_unlock("remote")
PostgreSQL(max.con = 2) # Set maximum simultaneous connections to 2
remote_db <- dbConnect(
  drv = PostgreSQL(),
  user = key_get("wrestling_username", keyring = "remote"),
  password = key_get("wrestling_password", keyring = "remote"),
  dbname = "mvhbdgdk",
  host = "manny.db.elephantsql.com"
)
keyring_lock("remote")
```

### List of Wrestlers

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers"
)
```

# Extensions

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE born = 'United Kingdom'"
)
```

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE born = 'Japan'
  AND total_matches >= 40"
)
```

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE win_percent BETWEEN 50 AND 60"
)
```

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE name LIKE 'X%'"
)
```

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE born LIKE 'I%'"
)
```

##

```{r}
dbGetQuery(
  remote_db,
  "SELECT * FROM wrestlers
  WHERE born NOT LIKE 'I%'"
)
```

```{r}
# Disconnect from remote_db
dbDisconnect(conn = remote_db)
```
